Repository pymeasure/pymeasure, pull requests merged in 2021-07, with the labels that each got.

#460 Documentation bugfix
  docs/tutorial/graphical.rst
  requirements/pymeasure.yml
Labels: bug

#383 Fix managed window
  docs/tutorial/graphical.rst
  pymeasure/display/browser.py
  pymeasure/display/curves.py
  pymeasure/display/manager.py
  pymeasure/display/widgets.py
  pymeasure/display/windows.py
Labels: bug

#199 BK Precision 9130B Instrument
  docs/api/instruments/bkprecision/bkprecision9130b.rst
  docs/api/instruments/bkprecision/index.rst
  pymeasure/instruments/bkprecision/__init__.py
  pymeasure/instruments/bkprecision/bkprecision9130b.py
Labels: enhancement

#198 Yokogawa GS200 Instrument
  docs/api/instruments/yokogawa/index.rst
  docs/api/instruments/yokogawa/yokogawags200.rst
  pymeasure/instruments/yokogawa/__init__.py
  pymeasure/instruments/yokogawa/yokogawags200.py
Labels: enhancement

#449 Implement visibility groups in `InputsWidgets`
  docs/tutorial/graphical.rst
  pymeasure/display/widgets.py
  pymeasure/display/windows.py
  pymeasure/experiment/parameters.py
Labels: GUI, enhancement
