Repository pymeasure/pymeasure, pull requests merged in 2024-11, with the labels that each got.

#1185 Add has_next method to Procedure class
  AUTHORS.txt
  pymeasure/display/manager.py
  pymeasure/experiment/procedure.py
  pymeasure/experiment/workers.py
Labels: automation

#1188 add "Reaveal in File Explorer" to browser item context menu
  pymeasure/display/windows/managed_window.py
Labels: GUI

#570 Support for Philips PM6669 Universal Frequency Counter
  docs/api/instruments/index.rst
  docs/api/instruments/philips/PM6669.rst
  docs/api/instruments/philips/index.rst
  pymeasure/instruments/philips/PM6669.py
  pymeasure/instruments/philips/__init__.py
  tests/instruments/philips/test_PM6669.py
  tests/instruments/philips/test_PM6669_with_device.py
Labels: stale
