Repository pymeasure/pymeasure, pull requests merged in 2024-05, with the labels that each got.

#1026 Support for numpy 2.0
  .github/pymeasure_numpy2.yml
  .github/workflows/pymeasure_CI.yml
  CHANGES.rst
  docs/quick_start.rst
  pymeasure/display/widgets/table_widget.py
  pymeasure/experiment/sequencer.py
  pymeasure/instruments/deltaelektronika/sm7045d.py
  pymeasure/instruments/fwbell/fwbell5080.py
  pymeasure/instruments/hp/hp856Xx.py
  pymeasure/instruments/oxfordinstruments/itc503.py
  setup.cfg
Labels: dependency

#1065 Fix toptica ibeamsmart referencing removed adapter function.
  pymeasure/instruments/toptica/ibeamsmart.py
Labels: bug, instrument

#1077 Make query_delay=None the default.
  pymeasure/instruments/aja/dcxs.py
  pymeasure/instruments/ametek/ametek7270.py
  pymeasure/instruments/attocube/anc300.py
  pymeasure/instruments/channel.py
  pymeasure/instruments/common_base.py
  pymeasure/instruments/instrument.py
  pymeasure/instruments/temptronic/temptronic_base.py
  pymeasure/instruments/thyracont/smartline_v2.py
  tests/instruments/temptronic/test_temptronic_base.py
  tests/instruments/test_instrument.py
Labels: bug, enhancement, instrument

#1088 Fix 1006 hp8116a
  pymeasure/instruments/hp/hp8116a.py
  tests/instruments/hp/test_hp8116a.py
  tests/instruments/test_all_instruments.py
Labels: instrument

#1051 Add Python 3.12 to pymeasure
  .github/pymeasure_python312.yml
  .github/workflows/pymeasure_CI.yml
  README.rst
  setup.cfg
  tests/instruments/test_all_instruments.py
Labels: enhancement

#1109 Fix temptronic test to use ns perf counter
  tests/instruments/temptronic/test_temptronic_base.py
Labels: bug, instrument

#1039 Make CI publish on release creation.
  .github/workflows/python-publish.yml
  RELEASE.md
Labels: enhancement

#1110 Fix temptronic test timing issue
  tests/instruments/temptronic/test_temptronic_base.py
Labels: bug

#1047 Add documentation for SCPI mixin
  docs/api/instruments/generic_types.rst
  docs/dev/adding_instruments/instrument.rst
Labels: documentation
